### ISSUE TITLE
datasource-identifiers fails to build, missing src/main/resources

### ISSUE THREAD

**Issue by croeder** [UCDenver-ccp/datasource#4]
--- maven-resources-plugin:2.6:resources (default-resources) @ datasource-identifiers ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/croeder/git-test/datasource.git/datasource-identifiers/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ datasource-identifiers ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 299 source files to /Users/croeder/git-test/datasource.git/datasource-identifiers/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] datasource ........................................ SUCCESS [0.294s]
[INFO] datasource-identifiers ............................ FAILURE [1.754s]
[INFO] datasource-fileparsers ............................ SKIPPED
[INFO] datasource-rdfizer ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

**Comment by sinistral** [comment]
Hello, Chris

Please could you check the error message that is reported after the "BUILD FAILURE" message. It may be that you're not building with Java 8, which is now required for this project.  Building without something like (on MacOS):

    >> export JAVA_HOME=$(/usr/libexec/java_home -v1.8)
    >> export PATH=$JAVA_HOME/bin:$PATH

Results in the following error:

    [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ datasource-identifiers ---
    [INFO] Using 'UTF-8' encoding to copy filtered resources.
    [INFO] skip non existing resourceDirectory /Users/marcdaya/Development/CCP/datasource.git/datasource-identifiers/src/main/resources
    [INFO]
    [INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ datasource-identifiers ---
    [INFO] Changes detected - recompiling the module!
    [INFO] Compiling 299 source files to /Users/marcdaya/Development/CCP/datasource.git/datasource-identifiers/target/classes
    [INFO] ------------------------------------------------------------------------
    [INFO] Reactor Summary:
    [INFO]
    [INFO] datasource ......................................... SUCCESS [  0.249 s]
    [INFO] datasource-identifiers ............................. FAILURE [  6.411 s]
    [INFO] datasource-fileparsers ............................. SKIPPED
    [INFO] datasource-rdfizer ................................. SKIPPED
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 6.926 s
    [INFO] Finished at: 2016-02-21T18:04:33-07:00
    [INFO] Final Memory: 11M/81M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project datasource-identifiers: Fatal error compiling: invalid target release: 1.8 -> [Help 1]
    [ERROR]
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.

Note the trailing errors after the build statistics.  Setting the JAVA_HOME and PATH variables as indicated above should fix this.

**Comment by croeder** [comment]
I added the missing directory and then saw a more direct message relating to java8. I installed java8. That seemed to run, however upon seeing the suggestion, I started fresh with java8 and see some other errors. I'll reply in detail after I spend some time with it. thanks for the reply.

**Comment by sinistral** [comment]
Are you still experiencing problems with the build, or can we close this issue?

**Comment by sinistral** [comment]
I'm closing this issue as it appears to be stale, but please reopen if you're still experiencing problems.

**Comment by croeder** [comment]
Thanks for the attention. My available time to spend here has been limited by my full time commitment, so I haven't been looking at this issue. It's not failing for me because I'm not trying, not necessarily because it works.

Good luck
-Chris
