### ISSUE TITLE
Unhandled synonym Type exception

### ISSUE THREAD

**Issue by skyladyyy** [UCDenver-ccp/datasource#5]
Hi, I'm using the edu.ucdenver.ccp.datasource.fileparsers.obo.OntologyUtil to build a conceptmapper dictionary for the NcbiTaxonomy. This raises the following exception

ERROR (OntologyUtil:193) Unhandled synonym type: <http://www.geneontology.org/formats/oboInOWL#hasRelatedSynonym>

The property value obtained from the OWLAnnotation is 
http://www.geneontology.org/formats/**oboInOWL**#hasRelatedSynonym>

while in line 59 of OntologyUtil.java you set it to "<http://www.geneontology.org/formats/**oboInOwl**#hasRelatedSynonym>"

that fails the matching since the property.equals(RELATED_SYN_PROP) is not case sensitive

**Comment by bill-baumgartner** [comment]
Hi there,

Thank you for reporting this issue. We have tracked it down to an inconsistency with which the OWL API OBO parser handles the oboInOwl namespace. Details can be found in the commit logs if you are interested. The OntologyUtil class has been updated to handle the inconsistency and should now be able to process the NCBI Taxonomy successfully. Please let us know if you run into further issues.

**Comment by skyladyyy** [comment]
Thank you!
